# -*- coding: utf-8 -*-
"""newsvendor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199wGjZGqzCqhC5s621_NQcubUxyRgT9V
"""

from scipy.stats import norm

p=45
h=25
ratio=p/(p+h)

val=norm.ppf(ratio)

mean=300
std=20
import sympy as sy
D=sy.symbols('D')
z=(D-mean)/std

sy.solve(z-val,D)

